name: tfjs_vis
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: chatree <chatree.srichart@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  js: ^0.6.1
  tfjs:
    path: /home/chatree/Projects/tfjs.dart

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
